name: CI

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: ${{ matrix.os }} ${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        version: ["stable"]

    steps:
      - uses: actions/checkout@v2

      - name: cargo test
        uses: actions-rs/cargo@v1
        timeout-minutes: 30
        with:
          command: test